//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeViewProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int MenuId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Population { get; set; }
        public Nullable<System.DateTime> EstablishedDate { get; set; }
        public string City { get; set; }
    }
}
